name: Create release from new tag

# this flow will be run only when new tags are pushed that match our pattern
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: ">=1.20.0"
            cache: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update go.sum
        run: go mod tidy
        
      - name: Build
        run: go build

      - name: Create GitHub release from tag
        uses: softprops/action-gh-release@v1
